services:
  mongodb:
    image: mongo:7.0
    container_name: kianda-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: kianda
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - kianda-network

volumes:
  mongodb_data:
    driver: local

networks:
  kianda-network:
    driver: bridge
